export async function getServerSideProps({ res }) {
  const base = process.env.NEXT_PUBLIC_URL || 'https://iskkollen.vercel.app';
  const pages = [{"path":"","priority":"1.0","changefreq":"daily"},{"path":"/om-oss","priority":"0.5","changefreq":"monthly"},{"path":"/kontakt","priority":"0.4","changefreq":"monthly"},{"path":"/integritetspolicy","priority":"0.3","changefreq":"yearly"},{"path":"/utan-avgift","priority":"0.8","changefreq":"weekly"},{"path":"/for-unga","priority":"0.8","changefreq":"weekly"},{"path":"/sparkonto","priority":"0.8","changefreq":"weekly"},{"path":"/isk","priority":"0.8","changefreq":"weekly"},{"path":"/utomlands","priority":"0.8","changefreq":"weekly"},{"path":"/jamfor/avanza-vs-nordnet","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/avanza-vs-revolut","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/avanza-vs-klarna","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/avanza-vs-lunar","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/avanza-vs-ica-banken","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/avanza-vs-handelsbanken","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/avanza-vs-n26","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordnet-vs-revolut","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordnet-vs-klarna","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordnet-vs-lunar","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordnet-vs-ica-banken","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordnet-vs-handelsbanken","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/nordnet-vs-n26","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/revolut-vs-klarna","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/revolut-vs-lunar","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/revolut-vs-ica-banken","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/revolut-vs-handelsbanken","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/revolut-vs-n26","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/klarna-vs-lunar","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/klarna-vs-ica-banken","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/klarna-vs-handelsbanken","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/klarna-vs-n26","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/lunar-vs-ica-banken","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/lunar-vs-handelsbanken","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/lunar-vs-n26","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/ica-banken-vs-handelsbanken","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/ica-banken-vs-n26","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/handelsbanken-vs-n26","priority":"0.7","changefreq":"weekly"}];
  const xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    pages.map(function(p) { return '<url><loc>'+base+p.path+'</loc><lastmod>2026-06-23</lastmod><changefreq>'+p.changefreq+'</changefreq><priority>'+p.priority+'</priority></url>'; }).join('') +
    '</urlset>';
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.write(xml); res.end();
  return { props: {} };
}
export default function Sitemap() { return null; }